Capybara fix n plus one
ahmidou09/blog_app pull request #8
Opened 2023-11-20 20:14 UTC by ahmidou09

This pull request addresses the following tasks:

- Fixed the N+1 problem in fetching all posts and their comments for a user.
- Added Capybara integration tests for each view in the project.
- Implemented pagination on the User Post Index page.

### Changes Made
- Analyzed app logs before and after the N+1 problem fix. Screenshots are attached.
- Wrote integration tests using Capybara for user index, user show, user post index, and post show pages.
- Implemented pagination for the User Post Index page to handle a large number of posts.

### Screenshots
- Before:
<img width="1057" alt="before_1" src="https://github.com/ahmidou09/blog_app/assets/122125958/3cd4d77d-e70b-4f56-8aee-0dce0bf52221">

- After:

<img width="1050" alt="after_1" src="https://github.com/ahmidou09/blog_app/assets/122125958/07a30f42-36da-49f5-b728-6aa9d047ba7b">

2023-11-20 20:35 UTC, mikethreels requested changes
Hi Mehdi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job writing the tests

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-20 20:35 UTC, mikethreels commented on spec/features/user_index_spec.rb
> +end
- [ ] It seems you haven't included the below test in this file:
- Tests that assert you can see the number of posts each user has written.

2023-11-20 20:35 UTC, mikethreels commented on spec/features/user_show_spec.rb
> +    expect(current_path).to eq(user_posts_path(user1))
- [ ] It seems you haven't included the below test in this file:
- Tests that asserts you can see the number of posts the user has written.

2023-11-20 20:35 UTC, mikethreels commented on spec/features/post_show_spec.rb
> +  end
- [ ] It seems you haven't included the below test in this file:
- Tests that assert you can see the username of each commentor.
- Tests that assert you can see the comment each commentor left.

2023-11-21 17:52 UTC, mukhammadrizooff approved these changes
Hi @ahmidou09, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

<img src="https://media4.giphy.com/media/sR9nilEznDoSlga667/giphy.gif"/> 

## Highlights
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-21 18:01 UTC, merged